print("Hello bank")
print("bank")
print("ice")
print("ice")
print("Hello bank")
print("bank")
print("ice")
print("ice")
print("Hello bank")
print("bank")
print("ice")
print("ice")
print("Hello bank")
print("bank")
print("ice")
print("ice")
